# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-09 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post2',
            name='f_choice',
            field=models.CharField(choices=[('TEXT', 'Text'), ('MARKDOWN', 'Markdown')], default='TEXT', max_length=8),
        ),
    ]
